"use client"
// components/anyfed/NewsBrief.tsx — Daily Brief: live federal FM intelligence
// (Neon DB, refreshed daily by the GitHub Action) filtered to the selected
// agency, with an on-demand AI executive brief: summary, insights, actions.
import { useEffect, useMemo, useState } from "react"
import { useTheme, Card, SectionTitle, Badge, Spinner } from "./ui"
import type { Agency } from "@/lib/agencies"

interface NewsItem {
  id: number; cat: string; urg: "HIGH" | "MEDIUM" | "LOW" | string
  headline: string; body: string; impact: string; src: string
  url?: string | null; time?: string; fetched_at?: string
  published_at?: string | null; agencies?: string | null
}

const URGS = ["ALL", "HIGH", "MEDIUM", "LOW"] as const

export default function NewsBrief({ agency }: { agency: Agency }) {
  const C = useTheme()
  const [news, setNews] = useState<NewsItem[] | null>(null)
  const [source, setSource] = useState<string>("")
  const [err, setErr] = useState<string | null>(null)
  const [onlyAgency, setOnlyAgency] = useState(true)
  const [urg, setUrg] = useState<(typeof URGS)[number]>("ALL")
  const [cat, setCat] = useState("ALL")
  const [brief, setBrief] = useState<{ text: string; model: string } | null>(null)
  const [briefing, setBriefing] = useState(false)

  useEffect(() => {
    fetch("/api/news-feed").then(r => r.json())
      .then(j => { setNews(j.news ?? []); setSource(j.source ?? "") })
      .catch(e => setErr(String(e)))
  }, [])
  useEffect(() => { setBrief(null) }, [agency.id])

  const tagsOf = (n: NewsItem) => (n.agencies ?? "").split(",").map(t => t.trim()).filter(Boolean)
  const relevant = (n: NewsItem) => {
    const t = tagsOf(n)
    return !t.length || t.includes("ALL") || t.includes(agency.id)
  }
  const cats = useMemo(() => ["ALL", ...Array.from(new Set((news ?? []).map(n => n.cat)))], [news])
  const filtered = useMemo(() => (news ?? []).filter(n =>
    (!onlyAgency || relevant(n)) && (urg === "ALL" || n.urg === urg) && (cat === "ALL" || n.cat === cat)),
    [news, onlyAgency, urg, cat, agency.id])  // eslint-disable-line react-hooks/exhaustive-deps

  const urgColor = (u: string) => u === "HIGH" ? C.red : u === "MEDIUM" ? C.gold : C.green

  const genBrief = async () => {
    if (briefing || !filtered.length) return
    setBriefing(true); setBrief(null)
    try {
      const digest = filtered.slice(0, 18).map((n, i) =>
        `${i + 1}. [${n.urg}] [${n.cat}] [${n.src}${n.published_at ? ` · ${n.published_at}` : ""}] ${n.headline}\n   impact: ${n.impact}`).join("\n")
      const content = `Today is ${new Date().toDateString()}. Below are today's federal FM intelligence items relevant to ${agency.name}.\n\n${digest}\n\nProduce the DAILY EXECUTIVE BRIEF for the ${agency.abbrev} CFO organization:\n1. BLUF — 2-3 sentences: what matters most today and why.\n2. TOP INSIGHTS — exactly 3, each tying one or more items to a concrete ${agency.abbrev} FM consequence (budget execution, audit, controls, acquisition), with the item number(s) cited like [3].\n3. RECOMMENDED ACTIONS — exactly 3, each with an owner role (e.g., Budget Officer, OCFO Audit Liaison) and a timeframe.\nKeep it under 320 words. No preamble.`
      const res = await fetch("/api/ai-chat", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: [{ role: "user", content }], agency: agency.id, task: "value" }),
      })
      const j = await res.json()
      if (!res.ok) throw new Error(j.error ?? `HTTP ${res.status}`)
      setBrief({ text: j.text, model: j.modelUsed })
    } catch (e) {
      setBrief({ text: `⚠️ ${e instanceof Error ? e.message : e}`, model: "" })
    } finally { setBriefing(false) }
  }

  const chip = (on: boolean, color: string): React.CSSProperties => ({
    padding: "6px 12px", borderRadius: 8, fontSize: 14.5, fontWeight: 700, cursor: "pointer",
    border: `1px solid ${on ? color : C.border}`, background: on ? `${color}1a` : C.card, color: on ? color : C.textSub })

  return (
    <div>
      <SectionTitle title="Daily Brief"
        sub={`Live federal FM intelligence for ${agency.name} — refreshed daily at ~6 AM ET by the GitHub Action (GAO · CBO · OMB/EOP · Federal Register per-agency feeds · GovExec · FedScoop), agency-tagged and impact-scored, with an AI executive brief on demand`} />

      {/* ── AI executive brief ── */}
      <Card title={`🧠 AI Executive Brief — ${agency.abbrev}, ${new Date().toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}`}
            sub="Summarizes the filtered items below into BLUF · 3 insights · 3 owned actions — generated by the agency-primed AI chain">
        {!brief && (
          <button onClick={genBrief} disabled={briefing || !filtered.length}
            style={{ padding: "10px 22px", borderRadius: 10, fontSize: 16.5, fontWeight: 800, cursor: filtered.length ? "pointer" : "not-allowed",
                     border: `1px solid ${C.borderAccent}`, background: `${C.blue}1f`, color: C.blue }}>
            {briefing ? "⏳ Analyzing today's items…" : `▶ Generate today's brief (${Math.min(filtered.length, 18)} items)`}
          </button>
        )}
        {brief && (
          <div>
            <div style={{ fontSize: 16.5, lineHeight: 1.7, color: C.text, whiteSpace: "pre-wrap" }}>{brief.text}</div>
            <div style={{ display: "flex", gap: 10, alignItems: "center", marginTop: 10, flexWrap: "wrap" }}>
              {brief.model && <Badge color={C.muted}>generated by {brief.model}</Badge>}
              <button onClick={() => { setBrief(null); genBrief() }}
                style={{ padding: "6px 14px", borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: "pointer",
                         border: `1px solid ${C.border}`, background: C.card, color: C.textSub }}>↻ Regenerate</button>
              <button onClick={() => navigator.clipboard?.writeText(brief.text)}
                style={{ padding: "6px 14px", borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: "pointer",
                         border: `1px solid ${C.border}`, background: C.card, color: C.textSub }}>⧉ Copy</button>
            </div>
          </div>
        )}
      </Card>
      <div style={{ height: 16 }} />

      {/* ── feed ── */}
      <Card title="📰 Intelligence feed" sub="urgency-scored, agency-tagged items — filters drive the AI brief above">
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", marginBottom: 12 }}>
          <button style={chip(onlyAgency, C.blue)} onClick={() => { setOnlyAgency(o => !o); setBrief(null) }}>
            {onlyAgency ? `◉ ${agency.abbrev}-relevant` : "○ all agencies"}</button>
          {URGS.map(u => (
            <button key={u} style={chip(urg === u, u === "ALL" ? C.cyan : urgColor(u))} onClick={() => { setUrg(u); setBrief(null) }}>{u}</button>
          ))}
          <select value={cat} onChange={e => { setCat(e.target.value); setBrief(null) }}
            style={{ background: C.card, color: C.text, border: `1px solid ${C.border}`, borderRadius: 8, padding: "7px 10px", fontSize: 14.5 }}>
            {cats.map(c2 => <option key={c2} value={c2}>{c2 === "ALL" ? "All categories" : c2}</option>)}
          </select>
          <span style={{ marginLeft: "auto", display: "flex", gap: 8, alignItems: "center" }}>
            <Badge color={source === "db" ? C.green : C.gold}>{source === "db" ? "● LIVE — Neon DB" : "◌ SAMPLE — DB not yet populated (Action seeds it daily)"}</Badge>
            <Badge color={C.cyan}>{filtered.length} items</Badge>
          </span>
        </div>

        {err && <div style={{ fontSize: 15, color: C.red }}>⚠️ {err}</div>}
        {!news && !err && <Spinner label="Loading intelligence feed…" />}
        {news && !filtered.length && <div style={{ fontSize: 15.5, color: C.muted }}>No items match — clear filters, or wait for the next daily fetch (the Action also runs on demand from the GitHub Actions tab).</div>}

        {filtered.map(n => (
          <div key={n.id} style={{ background: C.card, border: `1px solid ${C.border}`, borderLeft: `4px solid ${urgColor(n.urg)}`,
                                   borderRadius: 10, padding: "11px 14px", marginBottom: 10 }}>
            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 6 }}>
              <Badge color={urgColor(n.urg)}>{n.urg}</Badge>
              <Badge color={C.purple}>{n.cat}</Badge>
              <span style={{ fontSize: 13, color: C.muted }}>{n.src}{n.published_at ? ` · ${n.published_at}` : n.time ? ` · ${n.time}` : ""}</span>
              <span style={{ marginLeft: "auto", display: "flex", gap: 5, flexWrap: "wrap" }}>
                {tagsOf(n).slice(0, 5).map(t => (
                  <span key={t} style={{ fontSize: 11.5, fontWeight: 700, padding: "2px 8px", borderRadius: 6,
                                         background: t === agency.id ? `${C.green}1f` : `${C.muted}14`,
                                         color: t === agency.id ? C.green : C.muted, border: `1px solid ${t === agency.id ? C.green : C.border}` }}>{t}</span>
                ))}
              </span>
            </div>
            <div style={{ fontSize: 16.5, fontWeight: 700, color: C.text, lineHeight: 1.45, marginBottom: 5 }}>{n.headline}</div>
            {n.body && <div style={{ fontSize: 14.5, color: C.textSub, lineHeight: 1.6, marginBottom: 6 }}>{n.body}</div>}
            {n.impact && (
              <div style={{ fontSize: 14.5, color: C.cyan, lineHeight: 1.55 }}>
                💡 <b>FM impact:</b> {n.impact}
              </div>
            )}
            {n.url && <a href={n.url} target="_blank" rel="noreferrer" style={{ fontSize: 13.5, color: C.blue }}>View source →</a>}
          </div>
        ))}
      </Card>
    </div>
  )
}
